batch_size: 12
conf_thresh: 0.95
crop_size: 256
ctrl: age sex
data_desc: UKBB Train Data - 805 Patients, 80 Labeled, Rest Unlabeled Patients
data_root: /vol/aimspace/projects/ukbb/data/cardiac/cardiac_segmentations/subjects
dataset: ukbb
epochs: 50
lr: 0.01
mode: train
model_desc: Unimatch Unet 80 Training on UKBB
nclass: 4
num_workers: 1
seed: 73
split: 80
visualize: false
