batch_size: 12
conf_thresh: 0.95
crop_size: 256
data_root: /vol/aimspace/projects/ukbb/data/cardiac/cardiac_segmentations/subjects
dataset: ukbb
seg_model: unet
lr: 0.01
mode: train
nclass: 4
num_workers: 1
split: 18
seed: 42
visualize: False
nclass_classif: 3
task: multi_modal
epochs: 75
