model_desc: 'Unimatch Unet 80 Training on UKBB'
data_desc: 'UKBB Train Data - 805 Patients, 80 Labeled, Rest Unlabeled Patients'
ctrl: 'age sex'
split: 80
seed: 43

dataset: ukbb
mode: train
nclass: 4
crop_size: 256
data_root: /vol/aimspace/projects/ukbb/data/cardiac/cardiac_segmentations/subjects
num_workers: 1
visualize: False

epochs: 57
batch_size: 12 # 12 per GPU
lr: 0.01
conf_thresh: 0.95

labeled_split: splits/ukbb/80/labeled.csv
unlabeled_split: splits/ukbb/80/unlabeled.csv
train_split: splits/ukbb/80/train.csv
val_split: splits/ukbb/80/val.csv
all_split: splits/ukbb/all.csv