model_desc: 'Unimatch Unet 7 Training on ACDC'
data_desc: 'ADCD Train Data - 7 Labeled Patients, 63 Unlabeled Patients'

# arguments for dataset
dataset: acdc
nclass: 4
crop_size: 256
data_root: ACDC/

# arguments for training
epochs: 300
batch_size: 12 # 12 per GPU
lr: 0.01
conf_thresh: 0.95