model_desc: 'Unimatch Unet 7 Pretrained on ACDC'
data_desc: 'Test Data - 50 Patients'

mode: test
dataset: acdc
nclass: 4
crop_size: 256
data_root: ACDC/
batch_size: 1
num_workers: 2

model: 'exp/acdc/unimatch/unet/7/best.pth'
results_path: 'outputs/results/csv/unimatch_acdc_scores_test_50_patients.csv'
pred_mask_path: 'outputs/results/imgs/acdc/unimatch_acdc_pred_mask_'

