model_desc: 'Unimatch Unet 26 Training on UKBB'
data_desc: 'UKBB Train Data - 264 Patients, 26 Labeled, Rest Unlabeled Patients'
ctrl: 'age ethnicity'
split: 26

dataset: ukbb
mode: train
nclass: 4
crop_size: 256
data_root: /vol/aimspace/projects/ukbb/data/cardiac/cardiac_segmentations/subjects
num_workers: 1
visualize: False

epochs: 100
batch_size: 12 # 12 per GPU
lr: 0.01
conf_thresh: 0.95

labeled_split: splits/ukbb/26/labeled.csv
unlabeled_split: splits/ukbb/26/unlabeled.csv
train_split: splits/ukbb/26/train.csv
val_split: splits/ukbb/26/val.csv
all_split: splits/ukbb/all.csv