# arguments for dataset
dataset: ukbb
nclass: 4
crop_size: 256
data_root: /vol/aimspace/projects/ukbb/data/cardiac/cardiac_segmentation/subjects

# arguments for training
epochs: 300
batch_size: 12 # per GPU x 1 GPU
lr: 0.01
conf_thresh: 0.95
