model_desc: 'Unimatch Unet 7 Training on UKBB'
data_desc: 'UKBB Train Data - 7 Labeled Patients, 63 Unlabeled Patients'

dataset: ukbb
mode: test
nclass: 4
crop_size: 256
data_root: /vol/aimspace/projects/ukbb/data/cardiac/cardiac_segmentations/subjects
num_workers: 1

model: 'exp/acdc/unimatch/unet/7/best.pth'
results_path: 'outputs/results/csv/unimatch_ukbb_scores_test_1_patients.csv'
pred_mask_path: 'outputs/results/imgs/ukbb/unimatch_ukbb_pred_mask_'

# arguments for training
epochs: 300
batch_size: 12 # 12 per GPU
lr: 0.01
conf_thresh: 0.95

labeled_split: splits/ukbb/7/labeled.txt
unlabeled_split: splits/ukbb/7/unlabeled.txt
val_split: splits/ukbb/val.txt
test_split: splits/ukbb/test.txt
all_split: splits/ukbb/all.txt
all_csv: splits/ukbb/all.csv