model_desc: 'Unimatch Unet 7 Pretrained on UKBB - 70 Patients - 7 Labeled, 63 Unlabeled'
data_desc: 'UKBB Test Data - 1 Patients'

dataset: ukbb
mode: test
nclass: 4
crop_size: 256
data_root: /vol/aimspace/projects/ukbb/data/cardiac/cardiac_segmentations/subjects
batch_size: 1
num_workers: 1
visualize: True

model: 'exp/ukbb/unimatch/unet/7/best.pth'
results_path: 'outputs/results/csv/unimatch_ukbb_scores_1_patients.csv'
pred_mask_path: 'outputs/results/imgs/ukbb/unimatch_ukbb_pred_mask_'
test_split: splits/ukbb/test_one.txt
