# arguments for dataset
dataset: ukbb
nclass: 4
crop_size: 256
data_root: /vol/aimspace/projects/ukbb/data/cardiac/cardiac_segmentations/subjects

# arguments for training
epochs: 300
batch_size: 1 # 12 per GPU
lr: 0.01
conf_thresh: 0.95

# inference
model: 'exp/acdc/unimatch/unet/7/best.pth'
mode: test
results_path: 'outputs/results/csv/unimatch_ukbb_scores.csv'
pred_mask_path: 'outputs/results/imgs/ukbb/unimatch_ukbb_pred_mask_'
num_workers: 2
model_desc: 'Unimatch Unet 7 Pretrained on ACDC'
data_desc: 'Test Data - 1 Patients'