model_desc: 'Unimatch Unet 7 Pretrained on ACDC - 70 Patients - 7 Labeled, 63 Unlabeled'
data_desc: 'ACDC Test Data - 20 Patients'

mode: test
dataset: acdc
nclass: 4
crop_size: 256
data_root: ACDC/
batch_size: 1
num_workers: 1

model: 'exp/acdc/unimatch/unet/7/best.pth'
results_path: 'outputs/results/csv/unimatch_acdc_scores_20_patients.csv'
pred_mask_path: 'outputs/results/imgs/acdc/unimatch_acdc_pred_mask_'

