batch_size: 12
conf_thresh: 0.95
crop_size: 256
ctrl: age sex ethnicity
data_desc: UKBB Train Data - 182 Patients - 18 Labeled, Rest Unlabeled
data_root: /vol/aimspace/projects/ukbb/data/cardiac/cardiac_segmentations/subjects
dataset: ukbb
epochs: 200
lr: 0.01
mode: train
model_desc: Unimatch Unet 18 Training on UKBB
nclass: 4
num_workers: 1
seed: 47
split: 18
visualize: false
