model_desc: 'Unimatch Unet 330 Training on UKBB'
data_desc: 'UKBB Train Data - 3300 Patients, 330 Labeled, Rest Unlabeled Patients'
ctrl: 'none'
split: 26
seed: 42
dataset: ukbb
mode: train
nclass: 4
crop_size: 256
data_root: /vol/aimspace/projects/ukbb/data/cardiac/cardiac_segmentations/subjects
num_workers: 1
visualize: False
epochs: 50
batch_size: 12 # 12 per GPU
lr: 0.01
conf_thresh: 0.95