model_desc: 'Unimatch Unet 330 Training on UKBB'
data_desc: 'UKBB Train Data - 3300 Patients, 330 Labeled, Rest Unlabeled Patients'

dataset: ukbb
mode: train
nclass: 4
crop_size: 256
data_root: /vol/aimspace/projects/ukbb/data/cardiac/cardiac_segmentations/subjects
num_workers: 1
visualize: False

model: 'exp/acdc/unimatch/unet/330/best.pth'
results_path: 'outputs/results/csv/unimatch_ukbb_scores_test_1k_patients.csv'
pred_mask_path: 'outputs/results/imgs/ukbb/unimatch_ukbb_pred_mask_'

epochs: 60
batch_size: 12 # 12 per GPU
lr: 0.01
conf_thresh: 0.95

labeled_split: splits/ukbb/330/labeled.csv
unlabeled_split: splits/ukbb/330/unlabeled.csv
train_split: splits/ukbb/train.csv
val_split: splits/ukbb/val.csv
test_split: splits/ukbb/test.csv
all_split: splits/ukbb/all.csv