model_desc: 'Unimatch Unet 18 Training on UKBB'
data_desc: 'UKBB Train Data - 182 Patients - 18 Labeled, Rest Unlabeled'
ctrl: 'age sex ethnicity'
split: 18

dataset: ukbb
mode: train
nclass: 4
crop_size: 256
data_root: /vol/aimspace/projects/ukbb/data/cardiac/cardiac_segmentations/subjects
num_workers: 1
visualize: False

epochs: 200
batch_size: 12 # 12 per GPU
lr: 0.01
conf_thresh: 0.95

labeled_split: splits/ukbb/18/labeled.csv
unlabeled_split: splits/ukbb/18/unlabeled.csv
train_split: splits/ukbb/18/train.csv
val_split: splits/ukbb/18/val.csv
all_split: splits/ukbb/all.csv